Allow checking for custom handlers outside Dapper library
DapperLib/Dapper pull request #1405
Opened 2020-01-21 01:30 UTC by brendangooden

Allow checking for whether a type will be handled by a custom handlers outside Dapper library (For use in SimpleCRUD extension)

2020-02-13 22:53 UTC, brendangooden commented
Hi @NickCraver  any updates, can we merge this?

2021-05-09 14:51 UTC, NickCraver commented
With the caveat this will break heavily in vNext, no objections to adding it now that we know how severe that break will be. Do you mind filling in the xmldoc here and I'll get it in the next minor release?

2021-05-09 14:51 UTC, NickCraver requested changes

2021-05-09 14:51 UTC, NickCraver commented on Dapper/SqlMapper.cs
> +        /// <returns></returns>
Needs XML doc loving here please!

2021-05-09 21:27 UTC, brendangooden commented
@NickCraver done.

2021-05-09 23:08 UTC, NickCraver approved these changes
:+1: Thanks for the tweaks!

2021-05-09 23:12 UTC, merged