Fix/1480 fix ReadFirstOrDefaultAsync throw exception
DapperLib/Dapper pull request #1575
Opened 2020-11-19 08:09 UTC by zqlovejyc

2020-11-19 08:16 UTC, zqlovejyc commented
/usr/share/dotnet/sdk/3.1.403/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/runner/work/Dapper/Dapper/Dapper.Contrib/Dapper.Contrib.csproj]
  Dapper.Contrib -> /home/runner/work/Dapper/Dapper/Dapper.Contrib/bin/Release/netstandard2.0/Dapper.Contrib.dll
  Dapper.EntityFramework -> /home/runner/work/Dapper/Dapper/Dapper.EntityFramework/bin/Release/net461/Dapper.EntityFramework.dll
  Dapper.ProviderTools -> /home/runner/work/Dapper/Dapper/Dapper.ProviderTools/bin/Release/net461/Dapper.ProviderTools.dll
  Dapper.StrongName -> /home/runner/work/Dapper/Dapper/Dapper.StrongName/bin/Release/net461/Dapper.StrongName.dll
  Dapper.ProviderTools -> /home/runner/work/Dapper/Dapper/Dapper.ProviderTools/bin/Release/netstandard2.0/Dapper.ProviderTools.dll
/usr/share/dotnet/sdk/3.1.403/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/runner/work/Dapper/Dapper/Dapper.ProviderTools/Dapper.ProviderTools.csproj]
  Dapper.Rainbow -> /home/runner/work/Dapper/Dapper/Dapper.Rainbow/bin/Release/net461/Dapper.Rainbow.dll
  Dapper.Rainbow -> /home/runner/work/Dapper/Dapper/Dapper.Rainbow/bin/Release/netstandard2.0/Dapper.Rainbow.dll
  Dapper.EntityFramework.StrongName -> /home/runner/work/Dapper/Dapper/Dapper.EntityFramework.StrongName/bin/Release/net461/Dapper.EntityFramework.StrongName.dll
/usr/share/dotnet/sdk/3.1.403/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/runner/work/Dapper/Dapper/Dapper.Rainbow/Dapper.Rainbow.csproj]
  Dapper.SqlBuilder -> /home/runner/work/Dapper/Dapper/Dapper.SqlBuilder/bin/Release/net461/Dapper.SqlBuilder.dll
/usr/share/dotnet/sdk/3.1.403/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/runner/work/Dapper/Dapper/Dapper.SqlBuilder/Dapper.SqlBuilder.csproj]
  Dapper.StrongName -> /home/runner/work/Dapper/Dapper/Dapper.StrongName/bin/Release/netstandard2.0/Dapper.StrongName.dll
/usr/share/dotnet/sdk/3.1.403/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/runner/work/Dapper/Dapper/Dapper.StrongName/Dapper.StrongName.csproj]
/usr/share/dotnet/sdk/3.1.403/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/runner/work/Dapper/Dapper/Dapper/Dapper.csproj]
  Dapper.Tests.Performance -> /home/runner/work/Dapper/Dapper/benchmarks/Dapper.Tests.Performance/bin/Release/net462/Dapper.Tests.Performance.exe
/usr/share/dotnet/sdk/3.1.403/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/runner/work/Dapper/Dapper/tests/Dapper.Tests.Contrib/Dapper.Tests.Contrib.csproj]
  Dapper.SqlBuilder -> /home/runner/work/Dapper/Dapper/Dapper.SqlBuilder/bin/Release/netstandard2.0/Dapper.SqlBuilder.dll
  Dapper.Tests -> /home/runner/work/Dapper/Dapper/tests/Dapper.Tests/bin/Release/net462/Dapper.Tests.dll
/usr/share/dotnet/sdk/3.1.403/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/runner/work/Dapper/Dapper/tests/Dapper.Tests/Dapper.Tests.csproj]
  Dapper.Tests -> /home/runner/work/Dapper/Dapper/tests/Dapper.Tests/bin/Release/netcoreapp3.1/Dapper.Tests.dll
  Dapper.Tests -> /home/runner/work/Dapper/Dapper/tests/Dapper.Tests/bin/Release/net472/Dapper.Tests.dll
  Dapper.Tests.Contrib -> /home/runner/work/Dapper/Dapper/tests/Dapper.Tests.Contrib/bin/Release/netcoreapp3.1/Dapper.Tests.Contrib.dll
  Dapper.Tests.Contrib -> /home/runner/work/Dapper/Dapper/tests/Dapper.Tests.Contrib/bin/Release/net462/Dapper.Tests.Contrib.dll
  Dapper.Tests.Performance -> /home/runner/work/Dapper/Dapper/benchmarks/Dapper.Tests.Performance/bin/Release/netcoreapp3.1/Dapper.Tests.Performance.dll

2020-11-19 08:29 UTC, mgravell commented
Looks interesting; 2 thoughts:

1. "DRY" - it looks like the same logic 3 times; could this be a static utility method on `GridReader` ?
2. a test would be great - i.e. something that would fail without the fix, and now works

2020-11-19 08:30 UTC, mgravell commented
crossref; fixed #1480

2020-11-19 08:31 UTC, mgravell requested changes
- DRY
- needs example/test

2020-11-19 08:41 UTC, mgravell commented
@zqlovejyc  already reviewed - read up :)

2020-11-19 08:43 UTC, zqlovejyc commented
@mgravell What do I need to do next?

2020-11-19 09:05 UTC, mgravell commented
ideally:

1. move the thrice-repeated block of code to a static utility method, i.e.

``` c#
    private static T ConvertTo<T>(object value)
        => value switch
        {
            T typed => typed,
            null or DBNull => default,
            _ => (T)Convert.ChangeType(value, Nullable.GetUnderlyingType(typeof(T)) ?? typeof(T), CultureInfo.InvariantCulture),
        };
```

and use that in the various call-sites:

215: result = ConvertTo<T>(deserializer.Func(reader));
184: result = ConvertTo<T>(deserializer.Func(reader));
369: T result = ConvertTo<T>(deserializer(reader));

(there may be other paths that benefit from this, but that isn't your responsibility)

and for a test: we ideally need to show a scenario that now works, but which didn't before - i.e. a minimal repro of #1480 (I would then pull the test in isolation, check that it throws the error we're expecting, and then check that it no longer errors with the proposed changes)

2020-11-22 02:52 UTC, zqlovejyc commented
> ideally:
> 
> 1. move the thrice-repeated block of code to a static utility method, i.e.
> 
> ```cs
> private static T ConvertTo<T>(object value) => value switch {
>     T typed => typed,
>     null or DBNull => default,
>     _ => (T)Convert.ChangeType(value, Nullable.GetUnderlyingType(typeof(T)) ?? typeof(T), CultureInfo.InvariantCulture),
> };
> ```
> 
> and use that in the various call-sites:
> 
> 215: result = ConvertTo(deserializer.Func(reader));
> 184: result = ConvertTo(deserializer.Func(reader));
> 369: T result = ConvertTo(deserializer(reader));
> 
> (there may be other paths that benefit from this, but that isn't your responsibility)
> 
> and for a test: we ideally need to show a scenario that now works, but which didn't before - i.e. a minimal repro of #1480 (I would then pull the test in isolation, check that it throws the error we're expecting, and then check that it no longer errors with the proposed changes)

[DapperTest.zip](https://github.com/StackExchange/Dapper/files/5578837/DapperTest.zip)

2021-05-10 03:16 UTC, NickCraver commented
@mgravell I duplicated the efforts here after missing it the first time (several overlapping issues). Anyway, should now have tests that failed before and the DRY call all places involved here. Should be in good shape if you could give final eyes - or if game I'll just merge in.

2021-05-10 12:51 UTC, mgravell approved these changes

2021-05-10 12:58 UTC, merged